---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: exampleSite/content/english/blog
  label: 新闻
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/english/research
  label: 科研
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/english/notice
  label: 通知公告
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/english/contact
  label: 联系我们
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/english/course
  label: 课程设置
  create: all
  match: "**/*"
  templates:
  - course
- type: directory
  path: exampleSite/content/english/teacher
  label: 教职员工
  create: all
  match: "**/*"
  templates:
  - teacher
- type: directory
  path: exampleSite/content/english/history
  label: 历史沿革
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/english/about
  label: 关于我们
  create: all
  match: "**/*"
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
